var NPI = require('../src/NPI.js')
var npi = new NPI('1234567891')
console.log(npi)
console.log('The raw input is ' + npi.raw)
console.log('The non check digits are ' +npi.npi)
console.log('The check digit is '+ npi.checkDigit)
console.log('The NPI is valid: '+ npi.isValid)